{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bslib
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bslib_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bslib/bslib_{{ version }}.tar.gz
  sha256: b175612322e3ba929cf67a9261dd253346a981ce15bbb63d4a6874f54d5ef00e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-base64enc
    - r-cachem
    - r-htmltools >=0.5.4
    - r-jquerylib >=0.1.3
    - r-jsonlite
    - r-memoise >=2.0.1
    - r-mime
    - r-rlang
    - r-sass >=0.4.0
  run:
    - r-base
    - r-base64enc
    - r-cachem
    - r-htmltools >=0.5.4
    - r-jquerylib >=0.1.3
    - r-jsonlite
    - r-memoise >=2.0.1
    - r-mime
    - r-rlang
    - r-sass >=0.4.0

test:
  commands:
    - $R -e "library('bslib')"           # [not win]
    - "\"%R%\" -e \"library('bslib')\""  # [win]

about:
  home: https://rstudio.github.io/bslib/
  dev_url: https://github.com/rstudio/bslib
  doc_url: https://rstudio.github.io/bslib/reference/index.html
  license: MIT
  summary: Simplifies custom 'CSS' styling of both 'shiny' and 'rmarkdown' via 'Bootstrap' 'Sass'. Supports both 'Bootstrap' 3 and 4 as well as their various 'Bootswatch' themes. An interactive widget is also provided for previewing themes in real time.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
